name: Build my Application

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Print Current Directory
        run: pwd
      - name: List Filed in Directory
        run: ls
      - name: Check Dotnet CLI
        run: dotnet build
      - name: Check Dotnet CLI
        run: ls TrickingLibrary.API/ -R 
      - name: Check NPM CLI
        run: npm -v