name: Build my Application

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Print Current Directory
        run: pwd
      - name: List Filed in Directory
        run: ls